#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.15
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative "lexer"
  require_relative "../ast"

module GherkinRuby
  class Parser < Racc::Parser

module_eval(<<'...end gherkin.y/module_eval...', 'gherkin.y', 111)

  def parse(input)
    @yydebug = true if ENV['DEBUG_RACC']
    scan_str(input)
  end
...end gherkin.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    19,     4,     9,    19,    21,    10,    19,    10,    14,    10,
    46,    39,    40,    41,    42,    43,    19,     4,     9,    14,
    10,    39,    40,    41,    42,    43,    19,    14,    10,    14,
    10,    39,    40,    41,    42,    43,     4,    19,    21,    11,
    22,    10,    39,    40,    41,    42,    43,    19,    22,    25,
     4,    10,    27,    28,    30,    31,    22,    35,     4,     4,
    48,    22,     4,    51,    19,    52,     4,     4,     4,    19,
    19 ]

racc_action_check = [
    26,     0,     0,     5,     5,     0,    47,     5,     2,     2,
    26,    47,    47,    47,    47,    47,    50,     3,     3,    12,
    12,    50,    50,    50,    50,    50,    55,    17,    17,    33,
    33,    55,    55,    55,    55,    55,    16,    18,    18,     1,
    16,    18,    24,    24,    24,    24,    24,    32,     6,     7,
     8,    32,     9,    11,    14,    15,    20,    21,    25,    30,
    31,    34,    37,    38,    44,    45,    46,    48,    52,    53,
    57 ]

racc_action_pointer = [
    -1,    39,     3,    15,   nil,     1,    42,    45,    48,    40,
   nil,    53,    14,   nil,    42,    50,    34,    22,    35,   nil,
    50,    45,   nil,   nil,    35,    56,    -2,   nil,   nil,   nil,
    57,    48,    45,    24,    55,   nil,   nil,    60,    51,   nil,
   nil,   nil,   nil,   nil,    62,    53,    64,     4,    65,   nil,
    14,   nil,    66,    67,   nil,    24,   nil,    68,   nil ]

racc_action_default = [
   -38,   -38,    -1,   -38,    -5,   -38,    -7,   -10,   -12,   -38,
   -36,   -38,    -2,   -30,   -38,   -38,   -38,    -3,   -38,    -6,
    -8,   -38,   -37,   -11,   -38,   -38,   -13,   -15,    59,   -31,
   -38,   -38,   -34,    -4,    -9,   -16,   -19,   -21,   -38,   -25,
   -26,   -27,   -28,   -29,   -20,   -14,   -38,   -38,   -38,   -35,
   -22,   -24,   -38,   -17,   -32,   -38,   -23,   -18,   -33 ]

racc_goto_table = [
     5,    36,    29,    18,     6,    12,     1,     2,    26,    20,
    17,     3,    23,    45,    24,    49,    32,   nil,   nil,   nil,
    33,   nil,    34,    29,    54,    44,   nil,    56,   nil,   nil,
    47,   nil,    58,   nil,   nil,   nil,   nil,    50,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    53,   nil,    55,   nil,
   nil,   nil,    57 ]

racc_goto_check = [
     5,    12,    15,     5,     6,     3,     1,     2,     5,     6,
     2,     4,     8,    10,    11,    16,     5,   nil,   nil,   nil,
     3,   nil,     6,    15,    12,     5,   nil,    12,   nil,   nil,
     5,   nil,    12,   nil,   nil,   nil,   nil,     5,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,     5,   nil,
   nil,   nil,     5 ]

racc_goto_pointer = [
   nil,     6,     7,     3,    11,     0,     4,   nil,     5,   nil,
   -13,     7,   -23,   nil,   nil,   -10,   -17 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    16,     7,   nil,     8,
   nil,   nil,   nil,    37,    38,    13,    15 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 14, :_reduce_1,
  2, 14, :_reduce_2,
  2, 14, :_reduce_3,
  3, 14, :_reduce_4,
  1, 18, :_reduce_none,
  2, 18, :_reduce_none,
  1, 17, :_reduce_7,
  2, 17, :_reduce_8,
  3, 17, :_reduce_9,
  1, 15, :_reduce_10,
  2, 15, :_reduce_11,
  1, 20, :_reduce_12,
  2, 20, :_reduce_13,
  3, 20, :_reduce_14,
  2, 22, :_reduce_15,
  3, 22, :_reduce_16,
  2, 23, :_reduce_17,
  3, 23, :_reduce_18,
  2, 21, :_reduce_19,
  2, 24, :_reduce_20,
  1, 25, :_reduce_21,
  2, 25, :_reduce_22,
  3, 25, :_reduce_23,
  2, 26, :_reduce_24,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 16, :_reduce_30,
  2, 16, :_reduce_31,
  4, 28, :_reduce_32,
  5, 28, :_reduce_33,
  2, 29, :_reduce_34,
  3, 29, :_reduce_35,
  1, 19, :_reduce_36,
  2, 19, :_reduce_37 ]

racc_reduce_n = 38

racc_shift_n = 59

racc_token_table = {
  false => 0,
  :error => 1,
  :NEWLINE => 2,
  :FEATURE => 3,
  :BACKGROUND => 4,
  :SCENARIO => 5,
  :TAG => 6,
  :GIVEN => 7,
  :WHEN => 8,
  :THEN => 9,
  :AND => 10,
  :BUT => 11,
  :TEXT => 12 }

racc_nt_base = 13

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEWLINE",
  "FEATURE",
  "BACKGROUND",
  "SCENARIO",
  "TAG",
  "GIVEN",
  "WHEN",
  "THEN",
  "AND",
  "BUT",
  "TEXT",
  "$start",
  "Root",
  "Feature",
  "Scenarios",
  "FeatureTags",
  "Newline",
  "Tags",
  "FeatureHeader",
  "Background",
  "FeatureName",
  "Description",
  "BackgroundHeader",
  "Steps",
  "Step",
  "Keyword",
  "Scenario",
  "ScenarioTags" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'gherkin.y', 14)
  def _reduce_1(val, _values, result)
     result = val[0]; 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 17)
  def _reduce_2(val, _values, result)
     result = val[0]; result.scenarios = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 18)
  def _reduce_3(val, _values, result)
     result = val[1]; result.tags = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 20)
  def _reduce_4(val, _values, result)
     result = val[1]; result.scenarios = val[2]; result.tags = val[0] 
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'gherkin.y', 29)
  def _reduce_7(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 30)
  def _reduce_8(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 31)
  def _reduce_9(val, _values, result)
     result += val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 35)
  def _reduce_10(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 37)
  def _reduce_11(val, _values, result)
     result = val[0]; result.background = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 41)
  def _reduce_12(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 42)
  def _reduce_13(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 44)
  def _reduce_14(val, _values, result)
     result = val[0]; result.description = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 48)
  def _reduce_15(val, _values, result)
     result = AST::Feature.new(val[1]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 49)
  def _reduce_16(val, _values, result)
     result = AST::Feature.new(val[2]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 53)
  def _reduce_17(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 54)
  def _reduce_18(val, _values, result)
     result = val[0...-1].flatten 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 59)
  def _reduce_19(val, _values, result)
     result = val[0]; result.steps = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 63)
  def _reduce_20(val, _values, result)
     result = AST::Background.new; result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 67)
  def _reduce_21(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 68)
  def _reduce_22(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 69)
  def _reduce_23(val, _values, result)
     val[2].unshift(val[0]); result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 73)
  def _reduce_24(val, _values, result)
     result = AST::Step.new(val[1], val[0]); result.pos(filename, lineno) 
    result
  end
.,.,

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

module_eval(<<'.,.,', 'gherkin.y', 81)
  def _reduce_30(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 82)
  def _reduce_31(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 87)
  def _reduce_32(val, _values, result)
     result = AST::Scenario.new(val[1], val[3]); result.pos(filename, lineno - 1) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 90)
  def _reduce_33(val, _values, result)
     result = AST::Scenario.new(val[2], val[4], val[0]); result.pos(filename, lineno - 2) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 94)
  def _reduce_34(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 95)
  def _reduce_35(val, _values, result)
     result += val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 99)
  def _reduce_36(val, _values, result)
     result = [AST::Tag.new(val[0])] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 100)
  def _reduce_37(val, _values, result)
     result = val[0] << AST::Tag.new(val[1]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module GherkinRuby
