#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.2
# from Racc grammar file "".
#

require 'racc/parser.rb'

  require_relative "lexer"
  require_relative "../ast"

module GherkinRuby
  class Parser < Racc::Parser

module_eval(<<'...end gherkin.y/module_eval...', 'gherkin.y', 104)

  def parse(input)
    @yydebug = true if ENV['DEBUG_RACC']
    scan_str(input)
  end
...end gherkin.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    18,    36,    37,    38,    39,    40,    41,    18,    14,    10,
    11,    44,    36,    37,    38,    39,    40,    41,    18,    18,
     4,     9,    46,    36,    37,    38,    39,    40,    41,    18,
    14,    10,    14,    10,    36,    37,    38,    39,    40,    41,
     4,     9,    18,    20,    10,     4,    10,    18,    20,    21,
    14,    10,    21,    24,     4,    26,    27,    29,    21,    32,
     4,     4,     4,    48,    18,    49,     4,    52,     4,    18,
     4,    18 ]

racc_action_check = [
    25,    23,    23,    23,    23,    23,    23,    45,     2,     2,
     1,    25,    45,    45,    45,    45,    45,    45,    47,    30,
     3,     3,    30,    47,    47,    47,    47,    47,    47,    55,
    12,    12,    16,    16,    55,    55,    55,    55,    55,    55,
     0,     0,     5,     5,     0,    15,     5,    17,    17,    15,
    31,    31,     6,     7,     8,     9,    11,    14,    19,    20,
    24,    29,    34,    35,    42,    43,    44,    46,    49,    50,
    52,    54 ]

racc_action_pointer = [
    38,    10,     3,    18,   nil,    40,    46,    49,    52,    42,
   nil,    56,    25,   nil,    44,    43,    27,    45,   nil,    52,
    46,   nil,   nil,    -6,    58,    -2,   nil,   nil,   nil,    59,
    17,    45,   nil,   nil,    60,    50,   nil,   nil,   nil,   nil,
   nil,   nil,    62,    52,    64,     5,    54,    16,   nil,    66,
    67,   nil,    68,   nil,    69,    27,   nil ]

racc_action_default = [
   -36,   -36,    -1,   -36,    -5,   -36,    -7,    -9,   -11,   -36,
   -34,   -36,    -2,   -30,   -36,   -36,    -3,   -36,    -6,    -8,
   -36,   -35,   -10,   -36,   -36,   -12,   -14,    57,   -31,   -36,
   -36,    -4,   -15,   -18,   -20,   -36,   -24,   -25,   -26,   -27,
   -28,   -29,   -19,   -13,   -36,   -36,   -36,   -21,   -23,   -36,
   -16,   -32,   -36,   -22,   -17,   -36,   -33 ]

racc_goto_table = [
     5,    33,    28,    17,    12,     6,     2,     1,    25,    16,
    19,     3,    22,    43,    23,    30,   nil,   nil,    31,   nil,
   nil,    28,   nil,    51,    42,    53,   nil,   nil,   nil,    45,
   nil,   nil,   nil,    56,    47,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    50,   nil,   nil,   nil,   nil,    54,
   nil,   nil,    55 ]

racc_goto_check = [
     5,    12,    15,     5,     3,     6,     2,     1,     5,     2,
     6,     4,     8,    10,    11,     5,   nil,   nil,     3,   nil,
   nil,    15,   nil,    12,     5,    12,   nil,   nil,   nil,     5,
   nil,   nil,   nil,    12,     5,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,     5,
   nil,   nil,     5 ]

racc_goto_pointer = [
   nil,     7,     6,     2,    11,     0,     5,   nil,     5,   nil,
   -12,     7,   -22,   nil,   nil,   -10 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    15,     7,   nil,     8,
   nil,   nil,   nil,    34,    35,    13 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 15, :_reduce_1,
  2, 15, :_reduce_2,
  2, 15, :_reduce_3,
  3, 15, :_reduce_4,
  1, 19, :_reduce_none,
  2, 19, :_reduce_none,
  1, 18, :_reduce_7,
  2, 18, :_reduce_8,
  1, 16, :_reduce_9,
  2, 16, :_reduce_10,
  1, 21, :_reduce_11,
  2, 21, :_reduce_12,
  3, 21, :_reduce_13,
  2, 23, :_reduce_14,
  3, 23, :_reduce_15,
  2, 24, :_reduce_16,
  3, 24, :_reduce_17,
  2, 22, :_reduce_18,
  2, 25, :_reduce_19,
  1, 26, :_reduce_20,
  2, 26, :_reduce_21,
  3, 26, :_reduce_22,
  2, 27, :_reduce_23,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 17, :_reduce_30,
  2, 17, :_reduce_31,
  4, 29, :_reduce_32,
  6, 29, :_reduce_33,
  1, 20, :_reduce_34,
  2, 20, :_reduce_35 ]

racc_reduce_n = 36

racc_shift_n = 57

racc_token_table = {
  false => 0,
  :error => 1,
  :NEWLINE => 2,
  :FEATURE => 3,
  :BACKGROUND => 4,
  :SCENARIO => 5,
  :TAG => 6,
  :GIVEN => 7,
  :WHEN => 8,
  :THEN => 9,
  :AND => 10,
  :BUT => 11,
  :STAR => 12,
  :TEXT => 13 }

racc_nt_base = 14

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEWLINE",
  "FEATURE",
  "BACKGROUND",
  "SCENARIO",
  "TAG",
  "GIVEN",
  "WHEN",
  "THEN",
  "AND",
  "BUT",
  "STAR",
  "TEXT",
  "$start",
  "Root",
  "Feature",
  "Scenarios",
  "FeatureTags",
  "Newline",
  "Tags",
  "FeatureHeader",
  "Background",
  "FeatureName",
  "Description",
  "BackgroundHeader",
  "Steps",
  "Step",
  "Keyword",
  "Scenario" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'gherkin.y', 14)
  def _reduce_1(val, _values, result)
     result = val[0];
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 17)
  def _reduce_2(val, _values, result)
     result = val[0]; result.scenarios = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 18)
  def _reduce_3(val, _values, result)
     result = val[1]; result.tags = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 20)
  def _reduce_4(val, _values, result)
     result = val[1]; result.scenarios = val[2]; result.tags = val[0]
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'gherkin.y', 29)
  def _reduce_7(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 30)
  def _reduce_8(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 33)
  def _reduce_9(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 35)
  def _reduce_10(val, _values, result)
     result = val[0]; result.background = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 39)
  def _reduce_11(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 40)
  def _reduce_12(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 42)
  def _reduce_13(val, _values, result)
     result = val[0]; result.description = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 46)
  def _reduce_14(val, _values, result)
     result = AST::Feature.new(val[1]); result.pos(filename, lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 47)
  def _reduce_15(val, _values, result)
     result = AST::Feature.new(val[2]); result.pos(filename, lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 51)
  def _reduce_16(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 52)
  def _reduce_17(val, _values, result)
     result = val[0...-1].flatten
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 57)
  def _reduce_18(val, _values, result)
     result = val[0]; result.steps = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 61)
  def _reduce_19(val, _values, result)
     result = AST::Background.new; result.pos(filename, lineno)
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 65)
  def _reduce_20(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 66)
  def _reduce_21(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 67)
  def _reduce_22(val, _values, result)
     val[2].unshift(val[0]); result = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 71)
  def _reduce_23(val, _values, result)
     result = AST::Step.new(val[1], val[0]); result.pos(filename, lineno)
    result
  end
.,.,

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

module_eval(<<'.,.,', 'gherkin.y', 79)
  def _reduce_30(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 80)
  def _reduce_31(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 85)
  def _reduce_32(val, _values, result)
     result = AST::Scenario.new(val[1], val[3]); result.pos(filename, lineno - 1)
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 88)
  def _reduce_33(val, _values, result)
     result = AST::Scenario.new(val[3], val[5], val[0]); result.pos(filename, lineno - 2)
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 92)
  def _reduce_34(val, _values, result)
     result = [AST::Tag.new(val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 93)
  def _reduce_35(val, _values, result)
     result = val[0] << AST::Tag.new(val[1])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module GherkinRuby
